import { Vendor } from '@/types/vendor';

export const mockVendors: Vendor[] = [
  {
    id: 'v001',
    email: 'james.hartley@cleanpro.co.uk',
    phoneNumber: '+44 7700 900123',
    postcode: 'SW1A 1AA',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-01-05',
    status: 'Onboarded',
  },
  {
    id: 'v002',
    email: 'sophie.turner@brightwindows.co.uk',
    phoneNumber: '+44 7700 900456',
    postcode: 'EC1A 1BB',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-01-12',
    status: '-',
  },
  {
    id: 'v003',
    email: 'marcus.cole@valetking.co.uk',
    phoneNumber: '+44 7700 900789',
    postcode: 'W1A 0AX',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-01-19',
    status: 'Rejected',
  },
  {
    id: 'v004',
    email: 'priya.sharma@homehaven.co.uk',
    phoneNumber: '+44 7911 123456',
    postcode: 'N1 9GU',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-01-25',
    status: 'Onboarded',
  },
  {
    id: 'v005',
    email: 'liam.johnson@sparkleshine.co.uk',
    phoneNumber: '+44 7911 234567',
    postcode: 'SE1 7PB',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-02-02',
    status: 'Onboarded',
  },
  {
    id: 'v006',
    email: 'emma.watson@gleamclean.co.uk',
    phoneNumber: '+44 7911 345678',
    postcode: 'E1 6RF',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-02-08',
    status: 'Rejected',
  },
  {
    id: 'v007',
    email: 'oliver.brown@dustbusters.co.uk',
    phoneNumber: '+44 7700 987654',
    postcode: 'WC2N 5DU',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-02-14',
    status: 'Onboarded',
  },
  {
    id: 'v008',
    email: 'amelia.davis@clearview.co.uk',
    phoneNumber: '+44 7700 876543',
    postcode: 'SW3 4LY',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-02-20',
    status: 'Onboarded',
  },
  {
    id: 'v009',
    email: 'noah.wilson@autosheen.co.uk',
    phoneNumber: '+44 7700 765432',
    postcode: 'W8 5PT',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-02-27',
    status: 'Onboarded',
  },
  {
    id: 'v010',
    email: 'isabella.moore@tidyhomes.co.uk',
    phoneNumber: '+44 7700 654321',
    postcode: 'NW1 4NP',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-03-03',
    status: 'Rejected',
  },
  {
    id: 'v011',
    email: 'harry.taylor@windowwizards.co.uk',
    phoneNumber: '+44 7800 111222',
    postcode: 'EC2A 2BB',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-03-09',
    status: 'Onboarded',
  },
  {
    id: 'v012',
    email: 'grace.anderson@pristinecars.co.uk',
    phoneNumber: '+44 7800 222333',
    postcode: 'SE11 5RD',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-03-15',
    status: 'Onboarded',
  },
  {
    id: 'v013',
    email: 'jack.thomas@cleanspace.co.uk',
    phoneNumber: '+44 7800 333444',
    postcode: 'N7 8JP',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-03-21',
    status: 'Rejected',
  },
  {
    id: 'v014',
    email: 'mia.jackson@crystalclear.co.uk',
    phoneNumber: '+44 7800 444555',
    postcode: 'W6 9HR',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-03-28',
    status: 'Onboarded',
  },
  {
    id: 'v015',
    email: 'charlie.white@valethub.co.uk',
    phoneNumber: '+44 7800 555666',
    postcode: 'SW6 1AA',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-04-03',
    status: 'Onboarded',
  },
  {
    id: 'v016',
    email: 'ava.harris@homeclean.co.uk',
    phoneNumber: '+44 7800 666777',
    postcode: 'E14 9YT',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-04-09',
    status: 'Onboarded',
  },
  {
    id: 'v017',
    email: 'george.martin@shinewindows.co.uk',
    phoneNumber: '+44 7800 777888',
    postcode: 'N4 2DH',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-04-15',
    status: 'Rejected',
  },
  {
    id: 'v018',
    email: 'lily.thompson@cardazzle.co.uk',
    phoneNumber: '+44 7800 888999',
    postcode: 'SW10 9EL',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-04-21',
    status: 'Onboarded',
  },
  {
    id: 'v019',
    email: 'alfie.garcia@neatnest.co.uk',
    phoneNumber: '+44 7900 100200',
    postcode: 'WC1E 7HU',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-04-27',
    status: 'Onboarded',
  },
  {
    id: 'v020',
    email: 'ella.martinez@glassgenius.co.uk',
    phoneNumber: '+44 7900 200300',
    postcode: 'EC4M 5UT',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-05-03',
    status: 'Onboarded',
  },
  {
    id: 'v021',
    email: 'oscar.robinson@topvalet.co.uk',
    phoneNumber: '+44 7900 300400',
    postcode: 'SE5 8QT',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-05-09',
    status: 'Rejected',
  },
  {
    id: 'v022',
    email: 'poppy.clark@freshhome.co.uk',
    phoneNumber: '+44 7900 400500',
    postcode: 'W2 3QL',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-05-15',
    status: 'Onboarded',
  },
  {
    id: 'v023',
    email: 'william.rodriguez@sparkpane.co.uk',
    phoneNumber: '+44 7900 500600',
    postcode: 'N16 8EJ',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-05-21',
    status: 'Onboarded',
  },
  {
    id: 'v024',
    email: 'daisy.lewis@premiumvalet.co.uk',
    phoneNumber: '+44 7900 600700',
    postcode: 'SW7 2DT',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-05-27',
    status: 'Onboarded',
  },
  {
    id: 'v025',
    email: 'henry.lee@cozykeeping.co.uk',
    phoneNumber: '+44 7900 700800',
    postcode: 'E3 2NQ',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-06-03',
    status: 'Rejected',
  },
  {
    id: 'v026',
    email: 'freya.walker@cleanedge.co.uk',
    phoneNumber: '+44 7900 800900',
    postcode: 'NW3 1AA',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-06-09',
    status: 'Onboarded',
  },
  {
    id: 'v027',
    email: 'archie.hall@valetzone.co.uk',
    phoneNumber: '+44 7700 010203',
    postcode: 'SW4 6EB',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-06-15',
    status: 'Onboarded',
  },
  {
    id: 'v028',
    email: 'evie.allen@homepride.co.uk',
    phoneNumber: '+44 7700 020304',
    postcode: 'W4 1LZ',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-06-21',
    status: 'Onboarded',
  },
  {
    id: 'v029',
    email: 'teddy.young@windowexpert.co.uk',
    phoneNumber: '+44 7700 030405',
    postcode: 'EC3A 8BT',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-06-27',
    status: 'Rejected',
  },
  {
    id: 'v030',
    email: 'rosie.hernandez@shinedrive.co.uk',
    phoneNumber: '+44 7700 040506',
    postcode: 'SE17 3AQ',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-07-03',
    status: 'Onboarded',
  },
  {
    id: 'v031',
    email: 'reuben.king@swiftclean.co.uk',
    phoneNumber: '+44 7700 050607',
    postcode: 'N1C 4AG',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-07-09',
    status: 'Onboarded',
  },
  {
    id: 'v032',
    email: 'luna.wright@frameless.co.uk',
    phoneNumber: '+44 7700 060708',
    postcode: 'W10 5BN',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-07-15',
    status: 'Onboarded',
  },
  {
    id: 'v033',
    email: 'finn.scott@driveshine.co.uk',
    phoneNumber: '+44 7700 070809',
    postcode: 'SW11 2DD',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-07-21',
    status: 'Rejected',
  },
  {
    id: 'v034',
    email: 'nora.green.co.uk@sparkle.co.uk',
    phoneNumber: '+44 7700 080910',
    postcode: 'E8 1DY',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-07-27',
    status: 'Onboarded',
  },
  {
    id: 'v035',
    email: 'louis.adams@clearwindows.co.uk',
    phoneNumber: '+44 7700 091011',
    postcode: 'NW6 1LL',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-08-03',
    status: 'Onboarded',
  },
  {
    id: 'v036',
    email: 'zara.baker@ultrapolish.co.uk',
    phoneNumber: '+44 7700 101213',
    postcode: 'SW2 1RN',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-08-09',
    status: 'Onboarded',
  },
  {
    id: 'v037',
    email: 'sebastian.gonzalez@neathaven.co.uk',
    phoneNumber: '+44 7700 112233',
    postcode: 'W1D 3QY',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-08-15',
    status: 'Rejected',
  },
  {
    id: 'v038',
    email: 'harriet.nelson@glintglass.co.uk',
    phoneNumber: '+44 7700 223344',
    postcode: 'EC1V 2NX',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-08-21',
    status: 'Onboarded',
  },
  {
    id: 'v039',
    email: 'jude.carter@freshvalet.co.uk',
    phoneNumber: '+44 7700 334455',
    postcode: 'SE22 0RX',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-08-27',
    status: 'Onboarded',
  },
  {
    id: 'v040',
    email: 'millie.mitchell@homelux.co.uk',
    phoneNumber: '+44 7700 445566',
    postcode: 'SW15 2NU',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-09-03',
    status: 'Onboarded',
  },
  {
    id: 'v041',
    email: 'theo.perez@windowcraft.co.uk',
    phoneNumber: '+44 7700 556677',
    postcode: 'N8 9PQ',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-09-09',
    status: 'Rejected',
  },
  {
    id: 'v042',
    email: 'imogen.roberts@speedvalet.co.uk',
    phoneNumber: '+44 7700 667788',
    postcode: 'W9 2JQ',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-09-15',
    status: 'Onboarded',
  },
  {
    id: 'v043',
    email: 'rory.turner@tidiestuk.co.uk',
    phoneNumber: '+44 7700 778899',
    postcode: 'E1W 1AB',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-09-21',
    status: 'Onboarded',
  },
  {
    id: 'v044',
    email: 'penelope.phillips@sheenypanes.co.uk',
    phoneNumber: '+44 7700 889900',
    postcode: 'NW8 9PX',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-09-27',
    status: 'Onboarded',
  },
  {
    id: 'v045',
    email: 'monty.campbell@glowcars.co.uk',
    phoneNumber: '+44 7701 112233',
    postcode: 'SW8 2JX',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-10-03',
    status: 'Rejected',
  },
  {
    id: 'v046',
    email: 'clementine.evans@spothome.co.uk',
    phoneNumber: '+44 7701 223344',
    postcode: 'W14 8DH',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-10-09',
    status: 'Onboarded',
  },
  {
    id: 'v047',
    email: 'barnaby.edwards@panesplus.co.uk',
    phoneNumber: '+44 7701 334455',
    postcode: 'EC2Y 9AQ',
    vendorType: 'Independent',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-10-15',
    status: 'Onboarded',
  },
  {
    id: 'v048',
    email: 'ottoline.collins@supershine.co.uk',
    phoneNumber: '+44 7701 445566',
    postcode: 'SE4 1QX',
    vendorType: 'Company',
    serviceOffering: 'Car Valet',
    signupDate: '2024-10-21',
    status: 'Onboarded',
  },
  {
    id: 'v049',
    email: 'rupert.stewart@cleancrafter.co.uk',
    phoneNumber: '+44 7701 556677',
    postcode: 'N5 1LP',
    vendorType: 'Independent',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-10-27',
    status: 'Rejected',
  },
  {
    id: 'v050',
    email: 'thomasina.morris@brightpane.co.uk',
    phoneNumber: '+44 7701 667788',
    postcode: 'SW5 9NE',
    vendorType: 'Company',
    serviceOffering: 'Window Cleaning',
    signupDate: '2024-11-03',
    status: 'Onboarded',
  },
  {
    id: 'v051',
    email: 'jasper.rogers@autocleanse.co.uk',
    phoneNumber: '+44 7701 778899',
    postcode: 'W11 2QA',
    vendorType: 'Independent',
    serviceOffering: 'Car Valet',
    signupDate: '2024-11-09',
    status: 'Onboarded',
  },
  {
    id: 'v052',
    email: 'araminta.cook@homesheen.co.uk',
    phoneNumber: '+44 7701 889900',
    postcode: 'E2 7QH',
    vendorType: 'Company',
    serviceOffering: 'Housekeeping',
    signupDate: '2024-11-15',
    status: 'Onboarded',
  },
];